apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      containers:
      - name: migration
        image: busybox:1.36
        command: ["sh", "-c", "echo Running fake DB migration...; sleep 3; echo Migration complete!"]
      restartPolicy: Never
  backoffLimit: 2
